name: Job Hunter Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الكود
        uses: actions/checkout@v4

      - name: تشغيل بايثون
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تثبيت المكتبات
        run: |
          pip install feedparser requests

      - name: تشغيل البوت
        run: |
          python job_tracker.py
